// src/BiTechEditor.ts
import {
  ClassicEditor,
  Alignment,
  AutoImage,
  Autosave,
  BlockQuote,
  Bold,
  CloudServices,
  Code,
  CodeBlock,
  Essentials,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Fullscreen,
  GeneralHtmlSupport,
  Heading,
  Highlight,
  Image,
  ImageBlock,
  ImageInline,
  ImageInsert, // dùng dropdown chèn ảnh (kéo các phương thức có sẵn)
  ImageInsertViaUrl, // enable chèn ảnh qua URL
  ImageToolbar,
  ImageUpload, // nếu muốn upload (bạn có Base64 adapter custom)
  Indent,
  IndentBlock,
  Italic,
  Link,
  List,
  MediaEmbed,
  Paragraph,
  PlainTableOutput,
  SourceEditing,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableToolbar,
  Underline,
  Base64UploadAdapter,
  SelectAll,
} from "ckeditor5";

export const createBasicConfig = () => {
  return {
    licenseKey: "GPL",
    plugins: [
      Essentials,
      Paragraph,
      Bold,
      Italic,
      Heading,
      Link,
      Image,
      ImageUpload,
      Table,
      TableToolbar,
      Base64UploadAdapter,
      SelectAll,
      BlockQuote,
      CodeBlock,
      Alignment,
      Indent,
      IndentBlock,
      List,
      MediaEmbed,
      SourceEditing,
      Strikethrough,
      Subscript,
      Superscript,
      FontBackgroundColor,
      FontColor,
      FontFamily,
      FontSize,
      Highlight,
      Fullscreen,
      GeneralHtmlSupport,
      ImageBlock,
      ImageInline,
      ImageInsertViaUrl,
      ImageToolbar,
      ImageInsert,
      CloudServices,
      AutoImage,
      Table,
      TableToolbar,
      PlainTableOutput,
      TableCaption,
      SourceEditing,
      Underline,
      CloudServices,
      Autosave,
    ],
    toolbar: {
      items: [
        "undo",
        "redo",
        "|",
        "sourceEditing",
        "fullscreen",
        "|",
        "heading",
        "|",
        "fontSize",
        "fontFamily",
        "fontColor",
        "fontBackgroundColor",
        "|",
        "bold",
        "italic",
        "underline",
        "strikethrough",
        "subscript",
        "superscript",
        "code",
        "|",
        "link",
        "mediaEmbed",
        "insertTable",
        "highlight",
        "blockQuote",
        "codeBlock",
        "|",
        "alignment",
        "|",
        "bulletedList",
        "numberedList",
        "outdent",
        "indent",
        "|",
        "imageUpload",
      ],
      shouldNotGroupWhenFull: true,
    },
    image: {
      toolbar: [],
    },
    placeholder: "Nhập nội dung của bạn vào đây!",
    language: "vi",
  };
};
